concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
session_timeout = 1800

[[runners]]
name = "runner-host-nodejs"
url = "http://192.168.6.225"
id = 9
token = "glrt-coi57Pa2BQKziCx-fL2J"
token_obtained_at = 2024-09-04T13:51:59Z
token_expires_at = 1970-01-01T00:00:00Z
executor = "docker"
[runners.custom_build_dir]
[runners.cache]
MaxUploadedArchiveSize = 0
[runners.cache.s3]
[runners.cache.gcs]
[runners.cache.azure]
[runners.docker]
tls_verify = false
image = "node:20.17.0"
privileged = false
disable_entrypoint_overwrite = false
oom_kill_disable = false
disable_cache = false
volumes = ["/cache"]
shm_size = 0
network_mtu = 0

[[runners]]
name = "runner-go"
url = "http://192.168.6.225"
id = 10
token = "glrt-XozfBUFa5zYKSo576nfx"
token_obtained_at = 2024-09-04T13:56:13Z
token_expires_at = 1970-01-01T00:00:00Z
executor = "docker"
[runners.custom_build_dir]
[runners.cache]
MaxUploadedArchiveSize = 0
[runners.cache.s3]
[runners.cache.gcs]
[runners.cache.azure]
[runners.docker]
tls_verify = false
image = "golang:1.23"
privileged = false
disable_entrypoint_overwrite = false
oom_kill_disable = false
disable_cache = false
volumes = ["/cache"]
shm_size = 0
network_mtu = 0

[[runners]]
name = "Host-Runner-Shell"
url = "http://192.168.6.225"
id = 8
token = "glrt-QwTKgsQG_YvGmyxvu971"
token_obtained_at = 2024-09-05T01:59:18Z
token_expires_at = 1970-01-01T00:00:00Z
executor = "shell"
[runners.custom_build_dir]
[runners.cache]
MaxUploadedArchiveSize = 0
[runners.cache.s3]
[runners.cache.gcs]
[runners.cache.azure]
