version: "3.8"

services:
  gitlab-runner-golang:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner-golang
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/gitlab-runner
